version: "3.8"

services:
  blue:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_DIR: Blue
    container_name: blue_app
    ports:
      - "8081:80"
    restart: always

  green:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_DIR: Green
    container_name: green_app
    ports:
      - "8082:80"
    restart: always
