name: Blue-Green Deployment

on:
  push:
    branches:
      - main

env:
  GREEN_PORT: 8082  # default port for Green app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:alpine'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '0'
          ignore-unfixed: true

      ########################
      # DEPLOY TO BLUE SERVER
      ########################
      - name: Ensure bluegreen-app folder exists on Blue EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.BLUE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/bluegreen-app
            ls -l /home/ubuntu/bluegreen-app || true

      - name: Upload code to Blue EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.BLUE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/bluegreen-app"

      - name: Deploy blue_app on Blue EC2
        id: deploy_blue
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.BLUE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ubuntu/bluegreen-app
            ls -l
            sudo docker compose up -d --build blue

      ########################
      # DEPLOY TO GREEN SERVER
      ########################
      - name: Ensure bluegreen-app folder exists on Green EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GREEN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/bluegreen-app
            ls -l /home/ubuntu/bluegreen-app || true

      - name: Upload code to Green EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GREEN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/bluegreen-app"

      - name: Deploy green_app on Green EC2
        id: deploy_green
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GREEN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ubuntu/bluegreen-app
            ls -l
            sudo docker compose up -d --build green

      ########################
      # HEALTH CHECK ON GREEN
      ########################
      - name: Health Check on Green (via SSH)
        id: health
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GREEN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Performing health check on Green app..."
            curl --fail http://localhost:${{ env.GREEN_PORT }} || exit 1

      ########################
      # ENSURE NGINX ON PROXY (uses bluegreen.conf with failover logic)
      ########################
      - name: Ensure Nginx is installed and bluegreen.conf is enabled on Proxy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROXY_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            echo "📦 Installing Nginx if not present..."
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx

            echo "🔗 Linking bluegreen.conf to sites-enabled/current..."
            sudo ln -sf /etc/nginx/sites-available/bluegreen.conf /etc/nginx/sites-enabled/current

            echo "🧪 Testing Nginx configuration..."
            sudo nginx -t

            echo "🔄 Reloading Nginx with failover config..."
            sudo systemctl reload nginx

      ########################
      # DEPLOYMENT RESULT
      ########################
      - name: Print Deployment Result
        run: |
          if [ "${{ steps.health.outcome }}" == "success" ]; then
            echo "✅ Green deployed successfully. Proxy configured with failover."
          else
            echo "⚠️ Green deployment failed. Proxy still serves Blue via fallback."
          fi
