name: Manual Rollback to Blue

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Revert Nginx to Blue
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROXY_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Rolling back manually..."
          sudo sed -i 's/${{ secrets.GREEN_IP }}/${{ secrets.BLUE_IP }}/g' /etc/nginx/nginx.conf
          sudo systemctl reload nginx
